"""
Sample English text for training semantic representation models.
Text from Wikipedia about Natural Language Processing (approximately 800 words).
"""

SAMPLE_TEXT = """
Natural language processing is a machine learning technology that gives computers the ability to interpret, manipulate, and comprehend human language. Organizations today have large volumes of voice and text data from various communication channels like emails, text messages, social media newsfeeds, video, audio, and more. They use NLP software to automatically process this data, analyze the intent or sentiment in the message, and respond in real time to human communication.

Natural language processing helps computers communicate with humans in their own language and scales other language-related tasks. For example, NLP makes it possible for computers to read text, hear speech, interpret it, measure sentiment, and determine which parts are important. NLP combines computational linguistics, rule-based modeling of human language, with statistical, machine learning, and deep learning models. Together, these technologies enable computers to process human language in the form of text or voice data and understand its full meaning, complete with the speaker or writer's intent and sentiment.

Natural language processing plays a vital part in technology and the way humans interact with it. It is used in many real-world applications in both the business and consumer sectors, including digital assistants, speech recognition, and sentiment analysis. There are many common natural language processing tasks. One of them is speech recognition, which is the process of converting voice data into text data. Speech recognition is required for any application that follows voice commands or answers spoken questions. Speech recognition applications are valuable for individuals with disabilities, including those who are deaf or hard of hearing. Another important task is natural language generation, which is the process of turning structured data into text.

Sentiment analysis is a popular NLP task that involves determining the sentiment or emotion expressed in a piece of text. It is widely used in social media monitoring, customer feedback analysis, and market research. Sentiment analysis can help businesses understand public opinion about their products or services, allowing them to make data-driven decisions. Machine translation is another important application of natural language processing. It involves automatically translating text or speech from one language to another. Machine translation has revolutionized global communication, breaking down language barriers and enabling people to access information in different languages.

Named entity recognition is a task that involves identifying and categorizing named entities in text into predefined categories such as person names, organizations, locations, medical codes, time expressions, quantities, monetary values, and percentages. This task is fundamental in information extraction and plays a crucial role in many NLP applications. Text summarization is the process of creating a short, accurate, and fluent summary of a longer text document. It helps users quickly understand the main points of a document without reading the entire content. Text summarization can be extractive, where important sentences are selected from the original text, or abstractive, where new sentences are generated to capture the essence of the content.

Question answering systems are another important application of natural language processing. These systems are designed to answer questions posed in natural language. They use information retrieval and natural language understanding techniques to find answers from a knowledge base or a set of documents. Modern question answering systems are powered by large language models that can understand complex questions and generate accurate answers. Topic modeling is a technique used to discover abstract topics that occur in a collection of documents. It is commonly used for text mining, discovering hidden semantic structures in a text body, and organizing large collections of documents.

The field of natural language processing has seen tremendous advances in recent years, thanks to the development of deep learning techniques and large language models. These models, such as BERT, GPT, and their variants, have achieved state-of-the-art performance on many NLP tasks. They are trained on massive amounts of text data and can capture complex linguistic patterns and relationships. Word embeddings are a type of word representation that allows words with similar meaning to have a similar representation. They are a key breakthrough in the field of natural language processing and have enabled significant improvements in various NLP tasks.

Natural language processing continues to evolve and improve, with new techniques and models being developed regularly. As more data becomes available and computational power increases, NLP systems are becoming more sophisticated and capable. The future of natural language processing holds great promise, with potential applications in healthcare, education, customer service, and many other domains. Understanding and processing human language is one of the most challenging and exciting areas of artificial intelligence research, and natural language processing is at the forefront of this exciting field.
"""
